dartsconfig/urls.py
from django.contrib import admin
from django.urls import path, include

# Static files serve
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

# Allauth custom urls
from allauth.utils import importlib
from allauth.account.views import login, logout, signup
from allauth.socialaccount import providers

providers_urlpatterns = []

for provider in providers.registry.get_list():
    prov_mod = importlib.import_module(provider.get_package() + '.urls')
    providers_urlpatterns += getattr(prov_mod, 'urlpatterns', [])


urlpatterns = [
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("images/favicon.ico")),
    ),
    path('admin/', admin.site.urls),
    path('accounts/', include('user.urls')),
    path('accounts/signup/', signup, name="account_signup"),
    path('accounts/login/', login, name="account_login"),
    path('accounts/logout/', logout, name="account_logout"),
    path('accounts/', include(providers_urlpatterns)),
    # path('user/', include('django.contrib.auth.urls')),
    # path('accounts/', include('allauth.urls')),
    path('', include('darts.urls')), # disable this line for initial makemigrations
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

'''
Note that you do not necessarily need the URLs provided by django.contrib.auth.urls.
Instead of the URLs login, logout, and password_change (among others),
you can use the URLs provided by allauth: account_login, account_logout, account_set_password…
'''

user/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('players/', views.PlayerListView.as_view(), name='players'),
    path('players/create/', views.PlayerCreateView.as_view(), name='players_create'),
    path('players/update/<int:pk>/', views.PlayerUpdateView.as_view(), name='players_update'),
    path('players/delete/<int:pk>/', views.PlayerDeleteView.as_view(), name='players_delete'),
]

darts/models.py
from django.db import models
from user.models import Player
from django.contrib.auth import get_user_model
import uuid
    
    
class GameChoices(models.IntegerChoices):
    """ Game choices: 301, 501, Cricket, etc. """
    DARTS301 = 0, 'Standard 301'
    DARTS501 = 1, 'Standard 501'
    DARTS701 = 2, 'Standard 701'
    CRICKET = 3, 'Cricket'
    CRICKETCUT = 4, 'Cricket Cut Throat'


class GameSession(models.Model):    
    """ GameSessions are owned by CustomUser, one CustomUser can have many game sessions """
    uuid = models.UUIDField(unique=True, default=uuid.uuid4)
    game_type = models.IntegerField(choices=GameChoices.choices, default=GameChoices.DARTS501)
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    players = models.ManyToManyField(Player, related_name='game_session')
    time_created = models.DateTimeField(auto_now_add=True)
    time_modified = models.DateTimeField(auto_now=True)
    current_sum = models.IntegerField(default=0)
    scores = models.TextField()
    undo = models.TextField(default='{}')
    
    def __str__(self):
        return f'id:{self.id} owner:{self.owner} game_type:{self.game_type}'

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}<title>Darts Score</title>{% endblock title %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link href="{% static 'css/main.css' %}" rel="stylesheet" />
</head>
<body>
    {% include 'navbar.html' %}
    {% if messages %}
    <div class="container">
        <div class="row justify-content-md-center">
            <div class="alert alert-dark alert-dismissible fade show col-lg-10 mt-1 mb-1" role="alert">
                {% for message in messages %}{{ message }}{% endfor %}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        </div>
    </div>
    {% endif %}
    {% block content %}{% endblock content %}
    <footer class="form-signin w-100 m-auto text-center">
    <p class="mt-5 mb-3 text-muted">&copy; 2022–2023 by cvemir369</p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

templates/game_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<main class="form-signin w-100 m-auto text-left">
    <h1>New Game</h1>
    <p>Choose your game type and two of your players.</p>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-dark" type="submit">Start Game</button>
    </form>
</main>
{% endblock content %}

templates/game_delete.html
{% extends 'base.html' %}

{% block content %}
<main class="form-signin w-100 m-auto text-center">
    <h1 class="mt-2 mb-2">Delete Game</h1>
    <form action="" method="post">
        {% csrf_token %}
        <h3>Game Type: {{ game.get_game_type_display }}</h3>
        <p>Players: {% for player in game.players.all %} {{ player }},{% endfor %} created on {{ game.time_created|date:'d.m.Y. H:i' }}</p>
        <h3>Are you sure you want to delete this game?</h3>
        <button class="btn btn-danger" type="submit">Delete</button>
    </form>
    <div class="mt-2"><a class="link-dark" href="{% url 'play' uuid=game.uuid %}">Cancel, go back</a></div>
</main>
{% endblock content %}

templates/game_reset.html
{% extends 'base.html' %}

{% block content %}
<main class="form-signin w-100 m-auto text-center">
    <h1 class="mt-2 mb-2">Reset Game</h1>
    <h3>Are you sure you want to reset this game?</h3>
    <p>All stats will reset too.</p>
    <form action="" method="post">
        {% csrf_token %}
        <button class="btn btn-dark btn-block" type="submit">Reset</button>
    </form>
    <div class="mt-2"><a class="link-dark" href="{% url 'play' uuid=game.uuid %}">Cancel, go back</a></div>
</main>
{% endblock content %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<main class="form-signin w-100 m-auto text-center">
    <img class="mb-2" src="{% static 'images/darts.png' %}" alt="Darts" width="100">
    <h1 class="h1 mb-5 fw-normal">Welcome to Darts Score</h1>
    {% if games_count %}
    <div class="mt-2 mb-4">
        <a class="btn btn-dark" type="button" href="{% url 'game_create' %}">New game</a>
        <a class="btn btn-dark" type="button" href="{% url 'players' %}">Players</a>
    </div>
    <h1 class="h4 mb-2 fw-normal">Active games:</h1>
        {% for game in games %}
            <div class="list-group w-auto">
                <a href="{% url 'play' uuid=game.uuid %}" class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
                    <img src="{% static 'images/darts.png' %}" alt="Darts" width="35" height="35" class="rounded-circle flex-shrink-0">
                    <div class="d-flex gap-2 w-100 justify-content-between">
                        <div style="text-align: left;">
                            <h6 class="mb-0">{{ game.get_game_type_display }}</h6>
                            <p class="mb-0 opacity-75">{% for player in game.players.all %}{% if not forloop.last %}{{ player }} vs {% else %}{{ player }}{% endif %}{% endfor %}</p>
                        </div>
                        <small class="opacity-50 text-nowrap">modified on {{game.time_modified|date:'d.m.Y. H:i'}}</small>
                    </div>
                </a>
            </div>
        {% endfor %}
    {% elif players_count == 0 %}
        <h1 class="h5 mb-3 fw-normal">You don't have any players.<br>To start playing, create one now:</h1>
        <a class="btn btn-dark" type="submit" href="{% url 'players_create' %}">Create new player</a>
    {% elif players_count == 1 %}
        <h1 class="h5 mb-3 fw-normal">You have only one player. Create another one.</h1>
        <a class="btn btn-dark" type="submit" href="{% url 'players_create' %}">Create new player</a>
    {% else %}
        <h1 class="h5 mb-3 fw-normal">You don't have any games yet. Create one now.</h1>
        <a class="btn btn-dark" type="submit" href="{% url 'game_create' %}">Create new game</a>
    {% endif %}
</main>
    
{% endblock content %}

templates/navbar.html
{% load static %}
<header class="p-1 mb-1 border-bottom">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
            <img width="32px" src="{% static 'images/darts.png' %}" alt="Darts">
        </a>
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'home' %}" class="nav-link px-2 link-dark">Home</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'game_create' %}" class="nav-link px-2 link-dark">New game</a></li>
                <li><a href="{% url 'players' %}" class="nav-link px-2 link-dark">Players</a></li>
            {% else %}
                <li><a href="{% url 'account_login' %}" class="nav-link px-2 link-dark">Sign in</a></li>
            {% endif %}
        </ul>
        {% if user.is_authenticated %}
            <div class="p-2 small">Last login: {{ user.socialaccount_set.all.0.last_login|date:'d.m.Y. H:i'}}</div>   
            <div class="p-2">Hi, {{ user.socialaccount_set.all.0.extra_data.name }}!</div>
            <div class="dropdown text-end">
                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="{{ user.socialaccount_set.all.0.get_avatar_url }}" alt="mdo" width="32" height="32" class="rounded-circle">
                </a>
                <ul class="dropdown-menu text-small">
                <li><a class="dropdown-item" href="{% url 'game_create' %}">New game</a></li>
                <li><a class="dropdown-item" href="{% url 'players' %}">Players</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'account_logout' %}">Sign out</a></li>
                </ul>
            </div>
        {% endif %}
        </div>
    </div>
</header>

templates/play.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="form-play w-100 m-auto text-center">
  <div class="mt-2 mb-1">
    <a class="link-dark" href="{% url 'reset' uuid=active_game.uuid %}">Reset game</a> | 
    <a class="link-dark" href="{% url 'game_delete' uuid=active_game.uuid %}">Delete Game</a>
  </div>
  <!-- <p class="mb-1">Created on {{ active_game.time_created }}</p> -->
  <form class="mt-2 mb-2" action="" method="post">{% csrf_token %}
    <div class="mt-2 mb-1">
      <button class="btn btn-dark" type="submit" name="undo" value="undo">Undo last score</button>
      <button class="btn btn-dark" type="submit" name="next" value="next">Switch player</button>
      <br><small>Switch player doesn't affect stats.</small>
    </div>
  </form>
  <div class="table-score mt-1 mb-1">
    <table class="table">
      <thead>
        <tr>
          {% if p1_turn %}
          <th class="table-dark table-active-player"><h1>{{ p1_real_name }}</h1></th>
          <th class="table-dark"><img src="{% static 'images/dart_wh.png' %}" alt="Dart" width="20" style="transform:rotate(90deg)"></th>
          <th class="table-dark"><h1>{{ p2_real_name }}</h1></th>
          {% else %}
          <th class="table-dark"><h1>{{ p1_real_name }}</h1></th>
          <th class="table-dark"><img src="{% static 'images/dart_wh.png' %}" alt="Dart" width="20" style="transform:rotate(-90deg)"></th>
          <th class="table-dark table-active-player"><h1>{{ p2_real_name }}</h1></th>
          {% endif %}
        </tr>
      </thead>
        <tr><td colspan="3"></td></tr>
        <tr>
          <td><h1 class="table-points">{{ p1_points }}</h1></td>
          <th class="table-dark table-header">Points</th>
          <td><h1 class="table-points">{{ p2_points }}</h1></td>
        </tr>
      <tr>
        <td>{{ p1_games }}</td>
        <th class="table-dark table-header">Games</th>
        <td>{{ p2_games }}</td>
      </tr>
      <tr>
        <td>{{ p1_average }}</td>
        <th class="table-dark table-header">Game Avg.</th>
        <td>{{ p2_average }}</td>
      </tr>
      <tr>
        <td>{{ p1_average_total }}</td>
        <th class="table-dark table-header">Total Avg.</th>
        <td>{{ p2_average_total }}</td>
      </tr>
      <tr><td colspan="3"></td></tr>
      <tr><th colspan="3" class="table-dark table-header">{{ active_game.get_game_type_display }}, Double Out</th></tr>
    </table>
  </div>
  {% if checkout_show %}
    <h1 class="checkout mt-2 mb-2">{{ checkout }}</h1>
  {% endif %}
  <form class="mt-1 mb-1" action="" method="post">{% csrf_token %}
    <div class="btn-group mt-3 mb-2" role="group">
      <button class="btn btn-outline-dark" type="submit" name="1" value="1">1</button>
      <button class="btn btn-outline-dark" type="submit" name="2" value="2">2</button>
      <button class="btn btn-outline-dark" type="submit" name="3" value="3">3</button>
      <button class="btn btn-outline-dark" type="submit" name="4" value="4">4</button>
      <button class="btn btn-outline-dark" type="submit" name="5" value="5">5</button>
      <button class="btn btn-outline-dark" type="submit" name="6" value="6">6</button>
      <button class="btn btn-outline-dark" type="submit" name="7" value="7">7</button>
      <button class="btn btn-outline-dark" type="submit" name="8" value="8">8</button>
      <button class="btn btn-outline-dark" type="submit" name="9" value="9">9</button>
      <button class="btn btn-outline-dark" type="submit" name="10" value="10">10</button>
      <button class="btn btn-outline-dark" type="submit" name="11" value="11">11</button>
      <button class="btn btn-outline-dark" type="submit" name="12" value="12">12</button>
      <button class="btn btn-outline-dark" type="submit" name="13" value="13">13</button>
      <button class="btn btn-outline-dark" type="submit" name="14" value="14">14</button>
      <button class="btn btn-outline-dark" type="submit" name="15" value="15">15</button>
      <button class="btn btn-outline-dark" type="submit" name="16" value="16">16</button>
      <button class="btn btn-outline-dark" type="submit" name="17" value="17">17</button>
      <button class="btn btn-outline-dark" type="submit" name="18" value="18">18</button>
      <button class="btn btn-outline-dark" type="submit" name="19" value="19">19</button>
      <button class="btn btn-outline-dark" type="submit" name="20" value="20">20</button>
      <button class="btn btn-outline-dark" type="submit" name="25" value="25">Bull</button>
    </div>
    <br><small>Press buttons to calculate the score or enter manually below.</small>
    <p class="mt-1 mb-1">
      <button class="btn btn-secondary" type="submit" name="reset_counter" value="0">Score calculated: <b>{{ current_sum }}</b></button>
      {% if temp_checkout_show %}
      <b>{{ temp_checkout }}</b>
      {% endif %}
      <br><small>Click to reset to 0.</small>
    </p>
    <p>Enter score manually: <input type="number" min="0" max="180" name="score_manual" value="score_manual" autofocus></p>
    {% if checkout_show %}<p>Darts used for checkout: <input type="number" min="1" max="3" name="checkout_darts_used" value="3"></p>{% endif %}
    <button class="btn btn-success" type="submit" name="submit_score" value="submit_score"><b>Submit score</b></button>
    <button class="btn btn-danger" type="submit" name="bust" value="0">Bust, no score!</button>
  </form>
</main>
{% endblock content %}

templates/players_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<main class="form-signin w-100 m-auto text-left">
    <h1 class="mt-2 mb-2">New player</h1>
    <form class="mt-4 mb-4" action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-dark" type="submit">Create</button>
    </form>
</main>
{% endblock content %}

templates/players_delete.html
{% extends 'base.html' %}

{% block content %}
<main class="form-signin w-100 m-auto text-center">
    <h1 class="mt-2 mb-4">Delete player "{{ player }}"?</h1>
    <p>
        All related {{ player }}'s game sessions will be deleted too. <br>
       <strong style="color: red;">This can not be undone!</strong>
    </p>
    <h4 class="mt-4 mb-2">Are you sure?</h4>
    <form action="" method="post">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">Yes, delete</button>
    </form>
    <div class="mt-2"><a class="link-dark" href="{% url 'players' %}">Cancel, go back...</a></div>
</main>
{% endblock content %}

templates/players_list.html
{% extends 'base.html' %}

{% block content %}
<main class="form-signin w-100 m-auto text-center">
    <h1 class="mt-2 mb-2">{{ user.username|title }}'s Player List</h1>
    <a class="btn btn-dark mt-4 mb-4" type="button" href="{% url 'players_create' %}">Create new player</a>
    {% if players|length == 0 %}
        <p class="mt-2 mb-2">You don't have any players. Create one now.</p>
    {% else %}
        {% for player in players %}
        <div class="list-group w-auto">
            <div class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
                <div class="d-flex gap-2 w-100 justify-content-between">
                    <h6 class="mb-0">{{ player }}</h6>
                    <div>
                        <a class="link-dark mb-0" href="{% url 'players_update' player.pk %}">Edit</a> |
                        <a class="link-dark mb-0" href="{% url 'players_delete' player.pk %}">Delete</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    {% endif %}
</main>
{% endblock content %}
    

templates/players_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<main class="form-signin w-100 m-auto text-left">
    <h1 class="mt-2 mb-4">Update "{{ player }}"</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-dark" type="submit">Update</button>
    </form>
    <div class="mt-2"><a class="link-dark" href="{% url 'players' %}">Cancel, go back</a></div> 
</main>
{% endblock content %}